import type { SupportedCountry, TaxRules } from '@/types/global'

const SUPPORTED_COUNTRIES: SupportedCountry[] = [
  { code: 'US', name: 'United States', flag: '🇺🇸', currency: 'USD', supported: true, tier: 'full' },
  { code: 'NZ', name: 'New Zealand', flag: '🇳🇿', currency: 'NZD', supported: true, tier: 'full' },
  { code: 'AU', name: 'Australia', flag: '🇦🇺', currency: 'AUD', supported: true, tier: 'full' },
  { code: 'GB', name: 'United Kingdom', flag: '🇬🇧', currency: 'GBP', supported: true, tier: 'full' },
  { code: 'CA', name: 'Canada', flag: '🇨🇦', currency: 'CAD', supported: true, tier: 'full' },
  { code: 'DE', name: 'Germany', flag: '🇩🇪', currency: 'EUR', supported: true, tier: 'full' },
  { code: 'FR', name: 'France', flag: '🇫🇷', currency: 'EUR', supported: true, tier: 'full' },
  { code: 'JP', name: 'Japan', flag: '🇯🇵', currency: 'JPY', supported: true, tier: 'full' },
  { code: 'SG', name: 'Singapore', flag: '🇸🇬', currency: 'SGD', supported: true, tier: 'full' },
  { code: 'IN', name: 'India', flag: '🇮🇳', currency: 'INR', supported: true, tier: 'full' },
  { code: 'IE', name: 'Ireland', flag: '🇮🇪', currency: 'EUR', supported: true, tier: 'partial' },
  { code: 'NL', name: 'Netherlands', flag: '🇳🇱', currency: 'EUR', supported: true, tier: 'partial' },
  { code: 'SE', name: 'Sweden', flag: '🇸🇪', currency: 'SEK', supported: true, tier: 'partial' },
  { code: 'NO', name: 'Norway', flag: '🇳🇴', currency: 'NOK', supported: true, tier: 'partial' },
  { code: 'DK', name: 'Denmark', flag: '🇩🇰', currency: 'DKK', supported: true, tier: 'partial' },
  { code: 'CH', name: 'Switzerland', flag: '🇨🇭', currency: 'CHF', supported: true, tier: 'partial' },
  { code: 'ES', name: 'Spain', flag: '🇪🇸', currency: 'EUR', supported: true, tier: 'partial' },
  { code: 'IT', name: 'Italy', flag: '🇮🇹', currency: 'EUR', supported: true, tier: 'partial' },
  { code: 'PT', name: 'Portugal', flag: '🇵🇹', currency: 'EUR', supported: true, tier: 'partial' },
  { code: 'PL', name: 'Poland', flag: '🇵🇱', currency: 'PLN', supported: true, tier: 'partial' },
  { code: 'CZ', name: 'Czech Republic', flag: '🇨🇿', currency: 'CZK', supported: true, tier: 'partial' },
  { code: 'HU', name: 'Hungary', flag: '🇭🇺', currency: 'HUF', supported: true, tier: 'partial' },
  { code: 'RO', name: 'Romania', flag: '🇷🇴', currency: 'RON', supported: true, tier: 'partial' },
  { code: 'ZA', name: 'South Africa', flag: '🇿🇦', currency: 'ZAR', supported: true, tier: 'partial' },
  { code: 'MX', name: 'Mexico', flag: '🇲🇽', currency: 'MXN', supported: true, tier: 'partial' },
  { code: 'BR', name: 'Brazil', flag: '🇧🇷', currency: 'BRL', supported: true, tier: 'partial' },
  { code: 'AR', name: 'Argentina', flag: '🇦🇷', currency: 'ARS', supported: false, tier: 'coming_soon' },
  { code: 'CL', name: 'Chile', flag: '🇨🇱', currency: 'CLP', supported: false, tier: 'coming_soon' },
  { code: 'CO', name: 'Colombia', flag: '🇨🇴', currency: 'COP', supported: false, tier: 'coming_soon' },
  { code: 'KR', name: 'South Korea', flag: '🇰🇷', currency: 'KRW', supported: true, tier: 'partial' },
  { code: 'TH', name: 'Thailand', flag: '🇹🇭', currency: 'THB', supported: true, tier: 'partial' },
  { code: 'PH', name: 'Philippines', flag: '🇵🇭', currency: 'PHP', supported: true, tier: 'partial' },
  { code: 'MY', name: 'Malaysia', flag: '🇲🇾', currency: 'MYR', supported: true, tier: 'partial' },
  { code: 'ID', name: 'Indonesia', flag: '🇮🇩', currency: 'IDR', supported: false, tier: 'coming_soon' },
  { code: 'VN', name: 'Vietnam', flag: '🇻🇳', currency: 'VND', supported: false, tier: 'coming_soon' },
  { code: 'AE', name: 'United Arab Emirates', flag: '🇦🇪', currency: 'AED', supported: true, tier: 'partial' },
  { code: 'SA', name: 'Saudi Arabia', flag: '🇸🇦', currency: 'SAR', supported: false, tier: 'coming_soon' },
  { code: 'HK', name: 'Hong Kong', flag: '🇭🇰', currency: 'HKD', supported: true, tier: 'partial' },
  { code: 'TW', name: 'Taiwan', flag: '🇹🇼', currency: 'TWD', supported: false, tier: 'coming_soon' },
  { code: 'CN', name: 'China', flag: '🇨🇳', currency: 'CNY', supported: false, tier: 'coming_soon' },
  { code: 'UA', name: 'Ukraine', flag: '🇺🇦', currency: 'UAH', supported: false, tier: 'coming_soon' },
  { code: 'TR', name: 'Turkey', flag: '🇹🇷', currency: 'TRY', supported: false, tier: 'coming_soon' },
]

const TAX_RULES: Record<string, TaxRules> = {
  US: {
    id: 'us-2024',
    countryCode: 'US',
    countryName: 'United States',
    taxYear: 2024,
    federalTaxBrackets: [
      { minIncome: 0, maxIncome: 11600, rate: 0.10 },
      { minIncome: 11600, maxIncome: 47150, rate: 0.12 },
      { minIncome: 47150, maxIncome: 100525, rate: 0.22 },
      { minIncome: 100525, maxIncome: 191950, rate: 0.24 },
      { minIncome: 191950, maxIncome: 243725, rate: 0.32 },
      { minIncome: 243725, maxIncome: 609350, rate: 0.35 },
      { minIncome: 609350, maxIncome: null, rate: 0.37 },
    ],
    selfEmploymentTaxRate: 0.1530,
    standardDeduction: 14600,
    filingDeadline: 'April 15',
    currency: 'USD',
    forms: ['1040', 'Schedule C', 'Schedule SE', 'W-2', '1099-NEC'],
  },
  NZ: {
    id: 'nz-2024',
    countryCode: 'NZ',
    countryName: 'New Zealand',
    taxYear: 2024,
    federalTaxBrackets: [
      { minIncome: 0, maxIncome: 14000, rate: 0.105 },
      { minIncome: 14000, maxIncome: 48000, rate: 0.175 },
      { minIncome: 48000, maxIncome: 70000, rate: 0.30 },
      { minIncome: 70000, maxIncome: 180000, rate: 0.33 },
      { minIncome: 180000, maxIncome: null, rate: 0.39 },
    ],
    gstRate: 0.15,
    payeThreshold: 14000,
    filingDeadline: 'July 7',
    currency: 'NZD',
    forms: ['IR3', 'IR330', 'IR4', 'GST101A'],
  },
  AU: {
    id: 'au-2024',
    countryCode: 'AU',
    countryName: 'Australia',
    taxYear: 2024,
    federalTaxBrackets: [
      { minIncome: 0, maxIncome: 18200, rate: 0 },
      { minIncome: 18200, maxIncome: 45000, rate: 0.19 },
      { minIncome: 45000, maxIncome: 120000, rate: 0.325 },
      { minIncome: 120000, maxIncome: 180000, rate: 0.37 },
      { minIncome: 180000, maxIncome: null, rate: 0.45 },
    ],
    gstRate: 0.10,
    filingDeadline: 'October 31',
    currency: 'AUD',
    forms: ['Tax Return', 'BAS', 'TFN Declaration', 'ABN Application'],
  },
  GB: {
    id: 'gb-2024',
    countryCode: 'GB',
    countryName: 'United Kingdom',
    taxYear: 2024,
    federalTaxBrackets: [
      { minIncome: 0, maxIncome: 12570, rate: 0 },
      { minIncome: 12570, maxIncome: 50270, rate: 0.20 },
      { minIncome: 50270, maxIncome: 125140, rate: 0.40 },
      { minIncome: 125140, maxIncome: null, rate: 0.45 },
    ],
    vatRates: [{ region: 'GB', rate: 0.20 }],
    filingDeadline: 'January 31',
    currency: 'GBP',
    forms: ['SA100', 'SA103', 'P60', 'P45'],
  },
  CA: {
    id: 'ca-2024',
    countryCode: 'CA',
    countryName: 'Canada',
    taxYear: 2024,
    federalTaxBrackets: [
      { minIncome: 0, maxIncome: 55867, rate: 0.15 },
      { minIncome: 55867, maxIncome: 111733, rate: 0.205 },
      { minIncome: 111733, maxIncome: 154906, rate: 0.26 },
      { minIncome: 154906, maxIncome: 220000, rate: 0.29 },
      { minIncome: 220000, maxIncome: null, rate: 0.33 },
    ],
    gstRate: 0.05,
    filingDeadline: 'April 30',
    currency: 'CAD',
    forms: ['T1', 'T4', 'T2125', 'GST34'],
  },
  DE: {
    id: 'de-2024',
    countryCode: 'DE',
    countryName: 'Germany',
    taxYear: 2024,
    federalTaxBrackets: [
      { minIncome: 0, maxIncome: 11604, rate: 0 },
      { minIncome: 11604, maxIncome: 66760, rate: 0.14 },
      { minIncome: 66760, maxIncome: 277825, rate: 0.42 },
      { minIncome: 277825, maxIncome: null, rate: 0.45 },
    ],
    vatRates: [{ region: 'DE', rate: 0.19 }],
    filingDeadline: 'July 31',
    currency: 'EUR',
    forms: ['ESt 1 A', 'USt 1 A', 'Anlage S'],
  },
  FR: {
    id: 'fr-2024',
    countryCode: 'FR',
    countryName: 'France',
    taxYear: 2024,
    federalTaxBrackets: [
      { minIncome: 0, maxIncome: 11294, rate: 0 },
      { minIncome: 11294, maxIncome: 28797, rate: 0.11 },
      { minIncome: 28797, maxIncome: 82341, rate: 0.30 },
      { minIncome: 82341, maxIncome: 177106, rate: 0.41 },
      { minIncome: 177106, maxIncome: null, rate: 0.45 },
    ],
    vatRates: [{ region: 'FR', rate: 0.20 }],
    filingDeadline: 'May 31',
    currency: 'EUR',
    forms: ['2042', '2042 C', '2035'],
  },
  JP: {
    id: 'jp-2024',
    countryCode: 'JP',
    countryName: 'Japan',
    taxYear: 2024,
    federalTaxBrackets: [
      { minIncome: 0, maxIncome: 1950000, rate: 0.05 },
      { minIncome: 1950000, maxIncome: 3300000, rate: 0.10 },
      { minIncome: 3300000, maxIncome: 6950000, rate: 0.20 },
      { minIncome: 6950000, maxIncome: 9000000, rate: 0.23 },
      { minIncome: 9000000, maxIncome: 18000000, rate: 0.33 },
      { minIncome: 18000000, maxIncome: 40000000, rate: 0.40 },
      { minIncome: 40000000, maxIncome: null, rate: 0.45 },
    ],
    vatRates: [{ region: 'JP', rate: 0.10 }],
    filingDeadline: 'March 15',
    currency: 'JPY',
    forms: ['確定申告書', '源泉徴収票'],
  },
  SG: {
    id: 'sg-2024',
    countryCode: 'SG',
    countryName: 'Singapore',
    taxYear: 2024,
    federalTaxBrackets: [
      { minIncome: 0, maxIncome: 20000, rate: 0 },
      { minIncome: 20000, maxIncome: 30000, rate: 0.02 },
      { minIncome: 30000, maxIncome: 40000, rate: 0.035 },
      { minIncome: 40000, maxIncome: 80000, rate: 0.07 },
      { minIncome: 80000, maxIncome: 120000, rate: 0.115 },
      { minIncome: 120000, maxIncome: 160000, rate: 0.15 },
      { minIncome: 160000, maxIncome: 200000, rate: 0.18 },
      { minIncome: 200000, maxIncome: 240000, rate: 0.19 },
      { minIncome: 240000, maxIncome: 280000, rate: 0.195 },
      { minIncome: 280000, maxIncome: 320000, rate: 0.20 },
      { minIncome: 320000, maxIncome: 500000, rate: 0.22 },
      { minIncome: 500000, maxIncome: 1000000, rate: 0.23 },
      { minIncome: 1000000, maxIncome: null, rate: 0.24 },
    ],
    gstRate: 0.09,
    filingDeadline: 'April 18',
    currency: 'SGD',
    forms: ['Form B', 'Form B1', 'GST F5'],
  },
  IN: {
    id: 'in-2024',
    countryCode: 'IN',
    countryName: 'India',
    taxYear: 2024,
    federalTaxBrackets: [
      { minIncome: 0, maxIncome: 300000, rate: 0 },
      { minIncome: 300000, maxIncome: 600000, rate: 0.05 },
      { minIncome: 600000, maxIncome: 900000, rate: 0.10 },
      { minIncome: 900000, maxIncome: 1200000, rate: 0.15 },
      { minIncome: 1200000, maxIncome: 1500000, rate: 0.20 },
      { minIncome: 1500000, maxIncome: null, rate: 0.30 },
    ],
    gstRate: 0.18,
    filingDeadline: 'July 31',
    currency: 'INR',
    forms: ['ITR-1', 'ITR-3', 'ITR-4', 'Form 16'],
  },
}

export function getSupportedCountries(): SupportedCountry[] {
  return SUPPORTED_COUNTRIES
}

export function getTaxRules(countryCode: string): TaxRules | null {
  return TAX_RULES[countryCode.toUpperCase()] ?? null
}

export function getCountryByCode(countryCode: string): SupportedCountry | null {
  return SUPPORTED_COUNTRIES.find(c => c.code === countryCode.toUpperCase()) ?? null
}
