export interface BlogPost {
  slug: string
  title: string
  description: string
  date: string
  readTime: string
  category: string
  /** Service slug from lib/seo/servicesData — used for internal linking and FAQ schema */
  relatedServiceSlug?: string
}

const posts: BlogPost[] = [
  {
    slug: 'how-much-does-a-plumber-cost-in-nz',
    title: 'How Much Does a Plumber Cost in New Zealand? (2025 Guide)',
    description: 'Complete guide to plumber costs in NZ. Average prices, what affects cost, and how to get the best quotes.',
    date: '2025-04-01',
    readTime: '5 min read',
    category: 'Cost Guides',
    relatedServiceSlug: 'plumbing',
  },
  {
    slug: 'best-electricians-auckland',
    title: 'How to Find a Licensed Electrician in Auckland',
    description: 'What to look for when hiring an electrician in Auckland — licensing, costs, and how to get the best deal.',
    date: '2025-04-05',
    readTime: '4 min read',
    category: 'Hiring Guides',
    relatedServiceSlug: 'electrical',
  },
  {
    slug: 'how-to-hire-a-builder-new-zealand',
    title: 'How to Hire a Builder in New Zealand: The Complete Guide',
    description: 'Everything you need to know about hiring a builder in NZ — LBP requirements, contracts, quotes, and costs.',
    date: '2025-04-08',
    readTime: '6 min read',
    category: 'Hiring Guides',
    relatedServiceSlug: 'builder',
  },
  {
    slug: 'heat-pump-installation-cost-nz',
    title: 'Heat Pump Installation Cost in NZ: 2025 Price Guide',
    description: 'How much does it cost to install a heat pump in New Zealand? Complete price guide covering brands, sizes, installation costs and the Warmer Kiwi Homes subsidy.',
    date: '2025-04-10',
    readTime: '5 min read',
    category: 'Cost Guides',
    relatedServiceSlug: 'heat-pumps-air-conditioning',
  },
  {
    slug: 'house-cleaning-cost-nz',
    title: 'How Much Does House Cleaning Cost in NZ? (2025 Guide)',
    description: 'House cleaning prices in New Zealand — what you\'ll pay for regular, deep, and end-of-tenancy cleans in 2025.',
    date: '2025-04-11',
    readTime: '4 min read',
    category: 'Cost Guides',
    relatedServiceSlug: 'cleaning',
  },
  {
    slug: 'roof-repair-cost-nz',
    title: 'Roof Repair Costs in NZ: What to Expect in 2025',
    description: 'From minor leaks to full replacements — a complete guide to roof repair costs in New Zealand, including iron, tile and flat roofs.',
    date: '2025-04-12',
    readTime: '5 min read',
    category: 'Cost Guides',
    relatedServiceSlug: 'roofing',
  },
  {
    slug: 'painters-wellington',
    title: 'Finding a Painter in Wellington: Costs, Tips & What to Ask',
    description: 'Looking for a painter in Wellington? Here\'s what you\'ll pay, what questions to ask, and how to find a reliable local painter.',
    date: '2025-04-12',
    readTime: '4 min read',
    category: 'Local Guides',
    relatedServiceSlug: 'painting',
  },
  {
    slug: 'plumbers-christchurch',
    title: 'Plumbers in Christchurch: How to Find One & What It Costs',
    description: 'Need a plumber in Christchurch? Find out what plumbers charge in Canterbury, what jobs they do, and how to book fast on QuickTrade.',
    date: '2025-04-13',
    readTime: '4 min read',
    category: 'Local Guides',
    relatedServiceSlug: 'plumbing',
  },
  {
    slug: 'landscaping-cost-nz',
    title: 'Landscaping Costs in New Zealand: Full Price Guide (2025)',
    description: 'How much does landscaping cost in NZ? From lawn mowing to full garden makeovers — complete pricing guide for 2025.',
    date: '2025-04-13',
    readTime: '5 min read',
    category: 'Cost Guides',
    relatedServiceSlug: 'landscaping-gardening',
  },
  {
    slug: 'electricians-hamilton',
    title: 'Electricians in Hamilton: Costs, Licensing & How to Book',
    description: 'Looking for an electrician in Hamilton? Find out what registered electricians charge in Waikato and how to hire safely.',
    date: '2025-04-13',
    readTime: '4 min read',
    category: 'Local Guides',
    relatedServiceSlug: 'electrical',
  },
  {
    slug: 'handyman-services-auckland',
    title: 'Handyman Services in Auckland: What They Cost & How to Find One',
    description: 'Need a handyman in Auckland? Here\'s what handymen charge in Auckland, what jobs they can do, and how to find a reliable one fast.',
    date: '2025-04-13',
    readTime: '4 min read',
    category: 'Local Guides',
    relatedServiceSlug: 'handyman',
  },
  {
    slug: 'how-to-hire-a-plasterer-nz',
    title: 'How to Hire a Plasterer in New Zealand: Costs & What to Know',
    description: 'Everything you need to know about hiring a plasterer in NZ — gib stopping, crack repairs, costs and how to get the best finish.',
    date: '2025-04-13',
    readTime: '4 min read',
    category: 'Hiring Guides',
    relatedServiceSlug: 'plasterer',
  },
  {
    slug: 'moving-house-nz-checklist',
    title: 'Moving House in NZ: Complete Checklist & Removalist Costs (2025)',
    description: 'Moving house in New Zealand? Our complete checklist covers everything from booking removalists to changing your address — plus what it costs.',
    date: '2025-04-13',
    readTime: '6 min read',
    category: 'Hiring Guides',
    relatedServiceSlug: 'moving-removalists',
  },
  {
    slug: 'how-much-does-a-heat-pump-cost-nz',
    title: 'How Much Does a Heat Pump Cost in NZ? (2025 Guide)',
    description: 'Complete guide to heat pump supply and installation costs in New Zealand.',
    date: '2025-04-10',
    readTime: '5 min read',
    category: 'Cost Guides',
    relatedServiceSlug: 'heat-pumps-air-conditioning',
  },
  {
    slug: 'find-licensed-plumber-new-zealand',
    title: 'How to Find a Licensed Plumber in New Zealand',
    description: 'What to look for, certifications, and how to get competitive quotes.',
    date: '2025-04-12',
    readTime: '4 min read',
    category: 'Hiring Guides',
    relatedServiceSlug: 'plumbing',
  },
  {
    slug: 'best-handyman-services-nz',
    title: 'How to Hire a Reliable Handyman in New Zealand',
    description: 'Tips for finding vetted handymen, what jobs they can do, and typical rates.',
    date: '2025-04-16',
    readTime: '4 min read',
    category: 'Hiring Guides',
    relatedServiceSlug: 'handyman',
  },
  {
    slug: 'end-of-tenancy-cleaning-nz',
    title: 'End of Tenancy Cleaning in NZ: Costs and Checklist',
    description: 'Everything renters and landlords need to know about bond cleaning.',
    date: '2025-04-18',
    readTime: '5 min read',
    category: 'Cost Guides',
    relatedServiceSlug: 'cleaning',
  },
  {
    slug: 'deck-building-cost-nz',
    title: 'How Much Does a Deck Cost in New Zealand? (2025)',
    description: 'Timber vs composite, permits, and average prices per m².',
    date: '2025-04-20',
    readTime: '6 min read',
    category: 'Cost Guides',
  },
  {
    slug: 'hire-painter-new-zealand',
    title: 'How to Hire a Painter in NZ: Interior & Exterior Guide',
    description: 'What to ask, how paint quotes work, and red flags to avoid.',
    date: '2025-04-22',
    readTime: '4 min read',
    category: 'Hiring Guides',
    relatedServiceSlug: 'painting',
  },
  {
    slug: 'lawn-mowing-service-nz',
    title: 'Lawn Mowing Services in NZ: Prices, Frequency & Tips',
    description: 'How much lawn mowing costs and how to find a reliable gardener.',
    date: '2025-04-24',
    readTime: '3 min read',
    category: 'Cost Guides',
    relatedServiceSlug: 'landscaping-gardening',
  },
  {
    slug: 'electrician-call-out-fee-nz',
    title: 'What Is an Electrician Call-Out Fee in NZ?',
    description: 'Typical call-out fees, travel charges, and what\'s included.',
    date: '2025-04-26',
    readTime: '3 min read',
    category: 'Cost Guides',
    relatedServiceSlug: 'electrical',
  },
  {
    slug: 'home-renovation-cost-nz',
    title: 'How Much Does a Home Renovation Cost in NZ? (2025)',
    description: 'Kitchen, bathroom, and full-home reno price ranges across New Zealand.',
    date: '2025-04-28',
    readTime: '7 min read',
    category: 'Cost Guides',
  },
  {
    slug: 'how-to-find-a-reliable-electrician-nz',
    title: 'How to Find a Reliable Electrician in NZ: LBP Checks & Cost Guide',
    description: 'What to look for when hiring an electrician in New Zealand — LBP licence checks, average costs, and red flags to avoid.',
    date: '2026-04-01',
    readTime: '5 min read',
    category: 'Hiring Guides',
    relatedServiceSlug: 'electrical',
  },
  {
    slug: 'nz-building-consent-guide-2026',
    title: 'NZ Building Consent Guide 2026: When You Need It & What It Costs',
    description: 'Everything you need to know about building consents in New Zealand — when consent is required, how to apply, council fees, and timelines.',
    date: '2026-04-05',
    readTime: '6 min read',
    category: 'Hiring Guides',
    relatedServiceSlug: 'builder',
  },
  {
    slug: 'best-time-to-renovate-your-nz-home',
    title: 'Best Time to Renovate Your NZ Home: Seasonal Guide for Homeowners',
    description: 'When is the best time to renovate in New Zealand? A seasonal guide covering tradie availability, weather, costs, and planning tips.',
    date: '2026-04-10',
    readTime: '5 min read',
    category: 'Hiring Guides',
  },
  {
    slug: 'how-much-does-a-bathroom-renovation-cost-nz',
    title: 'How Much Does a Bathroom Renovation Cost in NZ? (2026 Price Guide)',
    description: 'Complete price breakdown for bathroom renovations in New Zealand — labour, materials, fittings, and what to budget for in 2026.',
    date: '2026-04-12',
    readTime: '6 min read',
    category: 'Cost Guides',
  },
  {
    slug: 'deck-building-costs-nz-2026',
    title: 'Deck Building Costs in NZ 2026: Timber vs Composite & Council Requirements',
    description: 'How much does it cost to build a deck in New Zealand in 2026? Timber vs composite materials, consent rules, and price per m².',
    date: '2026-04-15',
    readTime: '6 min read',
    category: 'Cost Guides',
  },
  {
    slug: 'find-tradies-tauranga',
    title: 'Find Trusted Tradies in Tauranga: Local Guide for Bay of Plenty Homeowners',
    description: 'Your complete guide to finding reliable tradespeople in Tauranga — plumbers, builders, electricians, and more in the Bay of Plenty.',
    date: '2026-04-18',
    readTime: '5 min read',
    category: 'Local Guides',
  },
  {
    slug: 'find-tradies-hamilton',
    title: 'Find Trusted Tradies in Hamilton: Local Guide for Waikato Homeowners',
    description: 'How to find reliable tradespeople in Hamilton — from electricians and plumbers to builders and painters in the Waikato region.',
    date: '2026-04-19',
    readTime: '5 min read',
    category: 'Local Guides',
  },
  {
    slug: 'solar-panel-installation-nz-guide',
    title: 'Solar Panel Installation in NZ: Costs, Payback Period & Best Installers (2026)',
    description: 'Complete guide to solar panel installation in New Zealand — system costs, payback periods, best brands, and how to find a certified installer.',
    date: '2026-04-20',
    readTime: '7 min read',
    category: 'Cost Guides',
    relatedServiceSlug: 'solar-installation',
  },
  {
    slug: 'landlord-maintenance-obligations-nz',
    title: 'Landlord Maintenance Obligations in NZ: Healthy Homes Standards Guide',
    description: 'What NZ landlords are legally required to maintain — Healthy Homes standards, urgent repairs, insulation rules, and tenant rights.',
    date: '2026-04-22',
    readTime: '6 min read',
    category: 'Hiring Guides',
  },
  {
    slug: 'plumbers-palmerston-north',
    title: 'Best Plumbers in Palmerston North — How to Choose',
    description: 'How to find a reliable, licensed plumber in Palmerston North. What to look for, what it costs, and how to get the best deal in Manawatū.',
    date: '2026-05-01',
    readTime: '5 min read',
    category: 'Local Guides',
    relatedServiceSlug: 'plumbing',
  },
  {
    slug: 'find-tradies-rotorua',
    title: 'Finding Trusted Tradies in Rotorua: A Complete Guide',
    description: 'Your complete guide to finding reliable tradespeople in Rotorua — plumbers, electricians, builders, and more in the Bay of Plenty.',
    date: '2026-05-01',
    readTime: '5 min read',
    category: 'Local Guides',
  },
  {
    slug: 'pest-control-nz-guide',
    title: 'Pest Control NZ: When to Call a Professional',
    description: 'How to know when a pest problem needs a professional in New Zealand — wasps, rodents, cockroaches, and more. Costs and what to expect.',
    date: '2026-05-01',
    readTime: '5 min read',
    category: 'Hiring Guides',
    relatedServiceSlug: 'pest-control',
  },
  {
    slug: 'home-insulation-nz-guide',
    title: 'Home Insulation NZ: Types, Costs, and What\'s Best for Your Home',
    description: 'Complete guide to home insulation in New Zealand — ceiling, underfloor, and wall insulation types, costs, and Healthy Homes requirements.',
    date: '2026-05-01',
    readTime: '6 min read',
    category: 'Cost Guides',
    relatedServiceSlug: 'insulation',
  },
  {
    slug: 'how-to-get-multiple-quotes-nz',
    title: 'How to Get Multiple Quotes for Home Jobs and Save Money',
    description: 'Step-by-step guide to getting multiple quotes from tradies in New Zealand — what to ask, how to compare, and how to save money on home jobs.',
    date: '2026-05-01',
    readTime: '4 min read',
    category: 'Hiring Guides',
  },
  {
    slug: 'hiring-a-cleaner-nz',
    title: 'Top Tips for Hiring a Cleaner in New Zealand',
    description: 'Everything you need to know about hiring a professional cleaner in NZ — what to look for, what it costs, and how to find someone you can trust.',
    date: '2026-05-01',
    readTime: '4 min read',
    category: 'Hiring Guides',
    relatedServiceSlug: 'cleaning',
  },
  // ── New posts ─────────────────────────────────────────────────────────────
  {
    slug: 'airtasker-alternative-nz',
    title: 'Best Airtasker Alternative in New Zealand: Why Kiwis Are Switching to QuickTrade',
    description: 'Looking for a better Airtasker alternative in NZ? See how QuickTrade compares — verified workers, transparent pricing, and built for New Zealand tradespeople.',
    date: '2026-05-10',
    readTime: '5 min read',
    category: 'Comparison',
  },
  {
    slug: 'spring-home-maintenance-checklist-nz',
    title: 'Spring Home Maintenance Checklist NZ: 12 Jobs to Book Now',
    description: 'Get your home ready for spring with our NZ home maintenance checklist — roof checks, heat pump servicing, gutter cleaning, and more. Book local tradies today.',
    date: '2026-05-10',
    readTime: '5 min read',
    category: 'Hiring Guides',
  },
  {
    slug: 'hire-construction-workers-nz',
    title: 'How to Hire Construction Workers in NZ: A Complete Employer Guide',
    description: 'Hiring construction staff in New Zealand? Everything employers need to know — where to find workers, employment law basics, and how to post jobs on QuickTrade.',
    date: '2026-05-10',
    readTime: '6 min read',
    category: 'Hiring Guides',
  },
  {
    slug: 'fence-installation-cost-nz',
    title: 'Fence Installation Cost NZ: 2026 Price Guide (Timber, Colorbond & More)',
    description: 'How much does fencing cost in New Zealand? Full price guide covering timber, Colorbond, and post-and-rail fences — per metre rates and what affects the price.',
    date: '2026-05-10',
    readTime: '5 min read',
    category: 'Cost Guides',
    relatedServiceSlug: 'fencing',
  },
  {
    slug: 'concrete-driveway-cost-nz',
    title: 'Concrete Driveway Cost NZ: What to Budget in 2026',
    description: 'How much does a concrete driveway cost in New Zealand? Average prices per m², what affects the cost, and tips for getting competitive quotes from local concreters.',
    date: '2026-05-10',
    readTime: '5 min read',
    category: 'Cost Guides',
    relatedServiceSlug: 'concreting',
  },
]

export function getAllPosts(): BlogPost[] {
  return posts
}

export function getPostBySlug(slug: string): BlogPost | undefined {
  return posts.find((p) => p.slug === slug)
}
